#!/usr/bin/env bash
dscl . read /Users/"$USER" Picture
test -z "$1" && exit
BASEDIR=$(dirname "$1")
BASEDIR=$(cd "$BASEDIR" && pwd -P)
NEW_IMG=$BASEDIR/$(basename "$1")
echo To be replaced by:
echo " $NEW_IMG"
read -r -p "Continue? [y/N]"
test "$REPLY" != "Y" -a "$REPLY" != "y" && exit
dscl . -changei /Users/"$USER" Picture 1 "$NEW_IMG"
dscl . -delete /Users/"$USER" JPEGPhoto
dscl . read /Users/"$USER" Picture
