#!/usr/bin/env bash
# set -x

TYPE="_smb._tcp."
SERVICES=$(
	(timeout 1s dns-sd -B "$TYPE" || true) | tail -n +5 | cut -c 74- | sort -u
)
SERVERS=$(
	echo "$SERVICES" | while read -r SERVICE; do
		SERVER=$(
			(timeout 1s dns-sd -L "$SERVICE" "$TYPE" || true) 2>&1 | grep 'can be reached' | awk '{$1=$1};1' | cut -d ' ' -f 2 | sort -u | sed -e's:\.$::'
		)
		echo "$SERVER"
	done
)
RESOURCES=$(
	echo "$SERVERS" | while read -r SERVER; do
		smbutil view -g "//$SERVER" | tail -n +3 | ghead -n -2 | awk '$2=="Disk" {print $1}' | xargs -n 1 -I % echo "$SERVER/%"
	done
)
if [ $# -eq 0 ]; then
	echo "$RESOURCES"
else
	while [ $# -gt 0 ]; do
		LOGIN=$(
			echo "$1" | cut -d '@' -f 1 -s
		)
		SEARCH=$(
			echo "$1" | cut -d '@' -f 2
		)
		shift
		MATCHES=$(
			echo "$RESOURCES" | grep "$SEARCH"
		)
		COUNT=$(
			echo -n "$MATCHES" | wc -w | tr -d ' \t'
		)
		if [ "$COUNT" -eq 0 ]; then
			MATCHES=$(
				echo "$RESOURCES" | grep -i "$SEARCH"
			)
			COUNT=$(
				echo -n "$MATCHES" | wc -w | tr -d ' \t'
			)
		fi
		case "$COUNT" in
		0)
			echo no match found for "$SEARCH"
			exit 1
			;;
		1)
			RESOURCE=$MATCHES
			echo found "$RESOURCE"
			MOUNTED=$(
				mount | grep -e "//.*$RESOURCE"
			)
			if [ -n "$MOUNTED" ]; then
				echo Already mounted as "$MOUNTED"
				exit 3
			fi
			if [ -n "$LOGIN" ]; then
				SERVERS=$(
					echo "$RESOURCE" | cut -d '/' -f 1
					echo "$RESOURCE" | cut -d '/' -f 1 | sed -e"s:$TYPE::" | tr "[:upper:]" "[:lower:]"
				)
				PASSWORD=$(
					security find-internet-password -r "smb " -s "$SERVER" -a "$LOGIN" -w
				)
				if [ -z "$PASSWORD" ]; then
					# https://git-scm.com/docs/git-credential
					# https://git-scm.com/docs/gitcredentials
					# https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/git-credential-lastpass
					# https://github.com/git/git/blob/master/contrib/credential/osxkeychain/git-credential-osxkeychain.c
					# https://github.com/frederick888/git-credential-keepassxc
					GIT_CREDENTIAL_HELPERS=$(
						git config -l | grep "credential.helper" | cut -d '=' -f 2
					)
					for PROTOCOL in smb https http; do
						for SERVER in $SERVERS; do
							for GIT_CREDENTIAL_HELPER in $GIT_CREDENTIAL_HELPERS; do
								PASSWORD=$(
									printf "protocol=%s\nhost=%s\nusername=%s\n" "$PROTOCOL" "$SERVER" "$LOGIN" |
										git credential-"$GIT_CREDENTIAL_HELPER" get |
										grep password |
										cut -c 10-
								)
								if [ -n "$PASSWORD" ]; then
									break
								fi
							done
							if [ -n "$PASSWORD" ]; then
								break
							fi
						done
						if [ -n "$PASSWORD" ]; then
							break
						fi
					done
				fi
				CREDENTIALS="$LOGIN:$PASSWORD"
			else
				CREDENTIALS="GUEST"
			fi
			osascript -e "mount volume \"smb://$CREDENTIALS@$RESOURCE\""
			;;
		*)
			echo found "$COUNT" matches for "$SEARCH"
			echo "$MATCHES"
			exit 2
			;;
		esac
	done
fi
